# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
    node: circleci/node@4.7.0
    codecov: codecov/codecov@3.1.0

jobs:
    test:
        docker:
            # replace with your preferred image
            - image: cimg/base:stable
        steps:
            - node/install:
                  install-npm: false
                  install-yarn: false
            - checkout
            - run:
                  name: Install pnpm package manager
                  command: |
                      curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@8
            - run: pnpm i
            - run: pnpm run test
            - run: pnpm run typeCheck
            - store_artifacts:
                  path: coverage
            - codecov/upload

workflows:
    test:
        jobs:
            - test
