# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

defaults: &defaults
    docker:
        - image: cimg/node:16.20.0

commands:
    prepare: &prepare
        steps:
            - checkout
            - run:
                  name: Install pnpm
                  command: npm install -g pnpm
            - run:
                  name: Install dependencies
                  command: pnpm install

jobs:
    test:
        <<: *defaults
        steps:
            - prepare
            - run:
                  name: Unit test
                  command: pnpm run test
            - run:
                  name: Build
                  command: pnpm run build

workflows:
    lint_and_build:
        jobs:
            - test

